name = "olfactoryops-api"
main = "worker/index.ts"
compatibility_date = "2026-07-10"
compatibility_flags = ["nodejs_compat"]
minify = true
workers_dev = true

[vars]
CORS_ORIGINS = "http://127.0.0.1:5173,http://localhost:5173,https://labofscents.org,https://www.labofscents.org,https://app.labofscents.org"

[[routes]]
pattern = "api.labofscents.org"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "olfactoryops-production"
database_id = "d70bc633-a4d8-4898-8149-d795032cf497"
migrations_dir = "migrations"
