import { readFileSync } from 'node:fs'
import { expect, test } from 'vitest'

const workflow = readFileSync('.github/workflows/v2-production-candidate-dispatch.yml', 'utf8')

function job(name, nextName) {
  const start = workflow.indexOf(`  ${name}:`)
  const end = nextName ? workflow.indexOf(`  ${nextName}:`, start) : workflow.length
  if (start < 0 || end < 0) throw new Error(`${name} is missing from the candidate dispatcher`)
  return workflow.slice(start, end)
}

test('candidate dispatcher accepts only the current release branch head', () => {
  const validation = job('validate-candidate-revision', 'deploy-candidate-pages')

  expect(validation).toContain('test "$RELEASE_SHA" = "$release_branch_sha"')
  expect(validation).not.toContain('git merge-base --is-ancestor')
  expect(validation).not.toContain('git tag --contains')
  expect(validation).toContain('candidate_acceptance_mode:')
  expect(validation).toContain('LEGACY_PRE_BOOTSTRAP')
  expect(validation).toContain('POST_BOOTSTRAP')
  expect(validation).toContain('test "$RELEASE_SHA" = "$RC10_SHA"')
  expect(validation).toContain('test "$OPERATION" = "smoke"')
})

test('candidate router derives the Pages origin from a validated isolated project', () => {
  const router = job('deploy-candidate-tenant-router', 'smoke-candidate')

  expect(router).toContain('[[ "$PRODUCTION_CANDIDATE_PAGES_PROJECT" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]]')
  expect(router).toContain('candidate_pages_origin="https://production-candidate.${PRODUCTION_CANDIDATE_PAGES_PROJECT}.pages.dev"')
  expect(router).toContain('export CANDIDATE_PAGES_ORIGIN="$candidate_pages_origin"')
  expect(router).toContain('candidate Pages origin is not the exact isolated Pages branch origin')
  expect(router).not.toContain('CANDIDATE_PAGES_ORIGIN: https://production-candidate.${{ vars.PRODUCTION_CANDIDATE_PAGES_PROJECT }}.pages.dev')
})

test('candidate smoke is fail-closed and has no legacy public-root configuration', () => {
  const smoke = job('smoke-candidate')
  const browserStart = smoke.indexOf('      - name: Verify the isolated candidate browser entrypoints')
  const installStart = smoke.indexOf('      - name: Install exact RC9 acceptance tooling', browserStart)
  const acceptanceStart = smoke.indexOf('      - name: Run bounded generated-fixture candidate acceptance')
  if (browserStart < 0 || installStart < 0 || acceptanceStart < 0) throw new Error('candidate browser or acceptance step is missing')
  const browser = smoke.slice(browserStart, installStart)
  const postBootstrapProof = smoke.slice(installStart, acceptanceStart)
  const acceptance = smoke.slice(acceptanceStart)
  const legacyStart = acceptance.indexOf('            LEGACY_PRE_BOOTSTRAP)')
  const postBootstrapStart = acceptance.indexOf('            POST_BOOTSTRAP)')
  if (legacyStart < 0 || postBootstrapStart < 0) throw new Error('candidate acceptance policy modes are missing')
  const legacyAcceptance = acceptance.slice(legacyStart, postBootstrapStart)
  const postBootstrapAcceptance = acceptance.slice(postBootstrapStart)

  expect(browser).toContain('V2_PRODUCTION_CANDIDATE_ACCEPTANCE_APPROVED: RUN_V2_PRODUCTION_CANDIDATE_ACCEPTANCE')
  expect(browser).toContain('V2_PRODUCTION_CANDIDATE_PROFILE: production-candidate')
  expect(browser).toContain('V2_PRODUCTION_CANDIDATE_API_ORIGIN: https://api-next.labofscents.org')
  expect(browser).toContain('V2_PRODUCTION_CANDIDATE_WORKSPACE_BASE_DOMAIN: next.labofscents.org')
  expect(browser).toContain('V2_PRODUCTION_CANDIDATE_TENANT_URL: ${{ vars.PRODUCTION_CANDIDATE_SMOKE_TENANT_URL }}')
  expect(browser).toContain('V2_PRODUCTION_CANDIDATE_EXPECTED_SHA: ${{ needs.validate-candidate-revision.outputs.release_sha }}')
  expect(browser).toContain('V2_PRODUCTION_CANDIDATE_FIXTURE_MODE: GENERATED_ISOLATED')
  expect(browser).toContain('npx playwright install --with-deps chromium')
  expect(smoke).toContain('path: ops')
  expect(smoke).toContain('path: rc9')
  expect(smoke).toContain('cache-dependency-path: |')
  expect(smoke).toContain('ops/package-lock.json')
  expect(smoke).toContain('rc9/package-lock.json')
  expect(browser).toContain('cd ops')
  expect(browser).toContain('node scripts/verify-v2-production-candidate-browser-acceptance.mjs')
  expect(browser).not.toContain('PRODUCTION_CANDIDATE_ACCEPTANCE_DATABASE_URL')
  expect(postBootstrapProof).toContain('PRODUCTION_CANDIDATE_ACCEPTANCE_DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}')
  expect(postBootstrapProof).toContain('verify-v2-production-owner-readiness.mjs')
  expect(postBootstrapProof).toContain('ACTIVE_PLATFORM_OWNER_COUNT=ONE')
  expect(postBootstrapProof).toContain('PLATFORM_OWNER_READY=PASS')
  expect(postBootstrapProof).toContain('REAL_PLATFORM_OWNER_PRESERVED=PASS')
  expect(acceptance).toContain('PRODUCTION_CANDIDATE_ACCEPTANCE_DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}')
  expect(acceptance).toContain('cd rc9')
  expect(acceptance).toContain('node scripts/verify-v2-production-candidate-acceptance.mjs --validate-only')
  expect(acceptance).toContain('npm run test:qa:v2-production-candidate-acceptance')
  expect(acceptance).toContain('CANDIDATE_ACCEPTANCE_MODE=LEGACY_PRE_BOOTSTRAP')
  expect(acceptance).toContain('POST_BOOTSTRAP)')
  expect(acceptance).toContain('prepare-v2-production-candidate-post-bootstrap-acceptance.mjs')
  expect(acceptance).toContain('rc10-post-bootstrap-candidate-acceptance')
  expect(acceptance).not.toContain('wrangler deploy')
  expect(acceptance).not.toContain('v2_platform_operators SET')
  expect(legacyAcceptance).toContain('npm run test:qa:v2-production-candidate-acceptance')
  expect(postBootstrapAcceptance).not.toContain('npm run test:qa:v2-production-candidate-acceptance')
  expect(postBootstrapAcceptance).toContain('test "$RELEASE_SHA" = "$RC10_SHA"')
  expect(postBootstrapAcceptance).toContain('node "$overlay"')
  expect(postBootstrapAcceptance).toContain('if: always()')
  expect(smoke).not.toContain('https://next.labofscents.org')
  expect(smoke).not.toContain('test:qa:production-smoke')
  expect(smoke).not.toContain('PRODUCTION_SMOKE_LOGIN_')
  expect(smoke).not.toContain('PRODUCTION_CANDIDATE_SMOKE_LOGIN_')
  expect(smoke).not.toContain('secrets.PRODUCTION_CANDIDATE_ACCEPTANCE_DATABASE_URL')
})
