import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'

type Locale = 'en-US' | 'vi-VN'
type V2Session = { user: { email: string; displayName: string; verified: boolean }; membership: { organizationName: string; organizationSlug: string; role: string }; capabilities: Record<string, boolean> }
type V2Invitation = { id: string; email: string; role: string; status: string; expiresAt: string; createdAt: string }

const apiBase = (import.meta.env.VITE_API_BASE_URL || '/api/v1').replace(/\/api\/v1\/?$/, '/api/v1/v2/platform')

const copy = {
  'en-US': {
    product: 'OlfactoryOps Platform', signIn: 'Sign in', signUp: 'Create workspace', email: 'Email', password: 'Password', name: 'Your name', workspace: 'Workspace name', slug: 'Workspace address', submitLogin: 'Sign in securely', submitSignup: 'Create workspace', security: 'Platform security', members: 'Members & roles', domains: 'Workspace domains', billing: 'Managed beta', notifications: 'Notifications', privacy: 'Privacy & exports', observability: 'Observability', loading: 'Loading workspace', verify: 'Check your inbox to verify this email before opening the workspace.', unavailable: 'Platform database is not configured for this environment.', switchSignup: 'Need a workspace?', switchLogin: 'Already have an account?', locale: 'VI', signOut: 'Sign out', status: 'Protected workspace', role: 'Role', address: 'System address', session: 'Sessions', export: 'Request personal export', consent: 'Record privacy consent', save: 'Save changes', back: 'Back to sign in', noAccess: 'This section is not available for your role.',
  },
  'vi-VN': {
    product: 'Nền tảng OlfactoryOps', signIn: 'Đăng nhập', signUp: 'Tạo workspace', email: 'Email', password: 'Mật khẩu', name: 'Tên của bạn', workspace: 'Tên workspace', slug: 'Địa chỉ workspace', submitLogin: 'Đăng nhập an toàn', submitSignup: 'Tạo workspace', security: 'Bảo mật nền tảng', members: 'Thành viên & vai trò', domains: 'Tên miền workspace', billing: 'Managed beta', notifications: 'Thông báo', privacy: 'Quyền riêng tư & xuất dữ liệu', observability: 'Quan sát hệ thống', loading: 'Đang tải workspace', verify: 'Hãy kiểm tra email để xác minh trước khi mở workspace.', unavailable: 'Database nền tảng chưa được cấu hình ở môi trường này.', switchSignup: 'Chưa có workspace?', switchLogin: 'Đã có tài khoản?', locale: 'EN', signOut: 'Đăng xuất', status: 'Workspace được bảo vệ', role: 'Vai trò', address: 'Địa chỉ hệ thống', session: 'Phiên đăng nhập', export: 'Yêu cầu xuất dữ liệu cá nhân', consent: 'Ghi nhận đồng ý quyền riêng tư', save: 'Lưu thay đổi', back: 'Quay lại đăng nhập', noAccess: 'Vai trò của bạn không có quyền xem phần này.',
  },
} as const
type PlatformCopy = { [K in keyof typeof copy['en-US']]: string }

function currentLocale(): Locale { return window.localStorage.getItem('olfactoryops.locale') === 'vi-VN' ? 'vi-VN' : 'en-US' }
function pathMode() { const path = window.location.pathname; if (path === '/v2/signup') return 'signup'; if (path === '/v2/login') return 'login'; if (path === '/v2/invitations/accept') return 'accept'; return 'workspace' }
function navigate(path: string) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const csrf = document.cookie.match(/(?:^|;\s*)oo_v2_csrf=([^;]+)/)?.[1] || window.localStorage.getItem('oo_v2_csrf') || undefined
  const response = await fetch(`${apiBase}${path}`, { ...init, credentials: 'include', headers: { 'Content-Type': 'application/json', ...(csrf ? { 'X-CSRF-Token': decodeURIComponent(csrf) } : {}), ...(init?.headers || {}) } })
  const payload = await response.json().catch(() => ({})) as { error?: { message?: string }; message?: string }
  if (!response.ok) throw new Error(payload.error?.message || payload.message || 'Request failed')
  return payload as T
}

export function V2PlatformApp() {
  const [locale, setLocale] = useState<Locale>(currentLocale)
  const [mode, setMode] = useState(pathMode)
  useEffect(() => { const onPop = () => setMode(pathMode()); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, [])
  const text = copy[locale]
  const toggleLocale = () => { const next = locale === 'en-US' ? 'vi-VN' : 'en-US'; window.localStorage.setItem('olfactoryops.locale', next); setLocale(next) }
  if (mode === 'login' || mode === 'signup') return <AuthView mode={mode} text={text} onLocale={toggleLocale} onNavigate={navigate} />
  if (mode === 'accept') return <InvitationAcceptView text={text} onLocale={toggleLocale} onNavigate={navigate} />
  return <WorkspaceView text={text} onLocale={toggleLocale} onNavigate={navigate} />
}

function InvitationAcceptView({ text, onLocale, onNavigate }: { text: PlatformCopy; onLocale: () => void; onNavigate: (path: string) => void }) {
  const [form, setForm] = useState({ token: '', email: '', displayName: '', password: '' })
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const result = await request<{ csrfToken?: string; workspaceUrl?: string }>('/auth/invitations/accept', { method: 'POST', body: JSON.stringify(form) }); if (result.csrfToken) window.localStorage.setItem('oo_v2_csrf', result.csrfToken); if (result.workspaceUrl && !['localhost', '127.0.0.1'].includes(window.location.hostname)) window.location.assign(result.workspaceUrl); else onNavigate('/v2/workspace') } catch (err) { setError(err instanceof Error ? err.message : text.unavailable) } finally { setBusy(false) } }
  return <main className="v2-platform-page"><div className="v2-platform-topbar"><strong>{text.product}</strong><div><button type="button" className="v2-text-button" onClick={onLocale}>{text.locale}</button><button type="button" className="v2-text-button" onClick={() => onNavigate('/v2/login')}>{text.signIn}</button></div></div><section className="v2-auth-card" data-testid="v2-invitation-accept"><span className="v2-eyebrow">{text.members}</span><h1>Accept invitation</h1><p>Use the invited email and one-time token to join this workspace.</p><form onSubmit={submit}><label>Invitation token<input required value={form.token} onChange={(e) => setForm({ ...form, token: e.target.value })} /></label><label>{text.email}<input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>{text.name}<input required value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} /></label><label>{text.password}<input type="password" required minLength={12} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label>{error ? <div className="v2-alert is-error" role="alert">{error}</div> : null}<button className="v2-primary-button" disabled={busy}>{busy ? text.loading : 'Accept invitation'}</button></form></section></main>
}

function AuthView({ mode, text, onLocale, onNavigate }: { mode: 'login' | 'signup'; text: PlatformCopy; onLocale: () => void; onNavigate: (path: string) => void }) {
  const [form, setForm] = useState({ email: '', password: '', displayName: '', organizationName: '', workspaceSlug: '' })
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); setNotice(null); try { if (mode === 'login') { const result = await request<{ csrfToken?: string; workspaceUrl?: string }>('/auth/login', { method: 'POST', body: JSON.stringify({ email: form.email, password: form.password }) }); if (result.csrfToken) window.localStorage.setItem('oo_v2_csrf', result.csrfToken); if (result.workspaceUrl && !['localhost', '127.0.0.1'].includes(window.location.hostname)) window.location.assign(result.workspaceUrl); else onNavigate('/v2/workspace') } else { const result = await request<{ csrfToken?: string; workspaceUrl?: string }>('/auth/signup', { method: 'POST', body: JSON.stringify(form) }); if (result.csrfToken) window.localStorage.setItem('oo_v2_csrf', result.csrfToken); setNotice(`${text.verify}${result.workspaceUrl ? ` ${result.workspaceUrl}` : ''}`) } } catch (err) { const message = err instanceof Error ? err.message : text.unavailable; setError(message.includes('not configured') ? text.unavailable : message) } finally { setBusy(false) } }
  return <main className="v2-platform-page"><div className="v2-platform-topbar"><strong>{text.product}</strong><div><button type="button" className="v2-text-button" onClick={onLocale}>{text.locale}</button><button type="button" className="v2-text-button" onClick={() => onNavigate(mode === 'login' ? '/v2/signup' : '/v2/login')}>{mode === 'login' ? text.signUp : text.signIn}</button></div></div><section className="v2-auth-card" data-testid="v2-auth-card"><span className="v2-eyebrow">{text.status}</span><h1>{mode === 'login' ? text.signIn : text.signUp}</h1><p>{mode === 'login' ? text.switchSignup : text.switchLogin}</p><form onSubmit={submit}>{mode === 'signup' ? <><label>{text.name}<input required value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} /></label><label>{text.workspace}<input required value={form.organizationName} onChange={(e) => setForm({ ...form, organizationName: e.target.value })} /></label><label>{text.slug}<input required value={form.workspaceSlug} onChange={(e) => setForm({ ...form, workspaceSlug: e.target.value })} /></label></> : null}<label>{text.email}<input type="email" required autoComplete="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>{text.password}<input type="password" required minLength={12} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label>{error ? <div className="v2-alert is-error" role="alert">{error}</div> : null}{notice ? <div className="v2-alert is-success" role="status">{notice}</div> : null}<button className="v2-primary-button" disabled={busy}>{busy ? text.loading : mode === 'login' ? text.submitLogin : text.submitSignup}</button></form></section></main>
}

function WorkspaceView({ text, onLocale, onNavigate }: { text: PlatformCopy; onLocale: () => void; onNavigate: (path: string) => void }) {
  const [session, setSession] = useState<V2Session | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState<string | null>(null); const [active, setActive] = useState(window.location.pathname.split('/').at(-1) || 'workspace')
  useEffect(() => { void request<V2Session>('/me').then(setSession).catch((err) => { setError(err instanceof Error ? err.message : text.unavailable); onNavigate('/v2/login') }).finally(() => setBusy(false)) }, [onNavigate, text.unavailable])
  const items = useMemo(() => [{ key: 'workspace', label: text.status, permission: 'tenant.view' }, { key: 'security', label: text.security, permission: 'security.sessions.view' }, { key: 'members', label: text.members, permission: 'members.view' }, { key: 'domains', label: text.domains, permission: 'domains.view' }, { key: 'billing', label: text.billing, permission: 'billing.capabilities' }, { key: 'notifications', label: text.notifications, permission: 'notifications.view' }, { key: 'privacy', label: text.privacy, permission: 'security.profile.view' }, { key: 'observability', label: text.observability, permission: 'observability.view' }].filter((item) => session?.capabilities?.[item.permission] === true), [session, text])
  if (busy) return <main className="v2-platform-page"><div className="v2-loading">{text.loading}</div></main>
  if (error && !session) return <main className="v2-platform-page"><div className="v2-auth-card"><div className="v2-alert is-error">{error}</div></div></main>
  const signOut = async () => { await request('/auth/logout', { method: 'POST' }).catch(() => undefined); onNavigate('/v2/login') }
  return <main className="v2-platform-page"><div className="v2-platform-topbar"><strong>{session?.membership.organizationName || text.product}</strong><div><button type="button" className="v2-text-button" onClick={onLocale}>{text.locale}</button><button type="button" className="v2-text-button" onClick={() => void signOut()}>{text.signOut}</button></div></div><div className="v2-workspace-layout"><aside className="v2-workspace-nav" aria-label="V2 workspace navigation">{items.map((item) => <button type="button" key={item.key} className={active === item.key ? 'is-active' : ''} onClick={() => { setActive(item.key); onNavigate(`/v2/workspace${item.key === 'workspace' ? '' : `/${item.key}`}`) }}>{item.label}</button>)}</aside><section className="v2-workspace-content" data-testid="v2-workspace"><span className="v2-eyebrow">{text.status}</span><h1>{session?.membership.organizationName}</h1><p className="v2-muted">{session?.user.email}</p><div className="v2-metric-grid"><div><span>{text.role}</span><strong>{session?.membership.role}</strong></div><div><span>{text.address}</span><strong>{session?.membership.organizationSlug}.olfactoryops.com</strong></div><div><span>{text.session}</span><strong>Protected</strong></div></div><V2Section active={active} text={text} session={session} /> </section></div></main>
}

function V2Section({ active, text, session }: { active: string; text: PlatformCopy; session: V2Session | null }) {
  const [notice, setNotice] = useState<string | null>(null)
  const [members, setMembers] = useState<Array<{ displayName: string; email: string; role: string; status: string }>>([])
  const [invitations, setInvitations] = useState<V2Invitation[]>([])
  const [inviteForm, setInviteForm] = useState({ email: '', role: 'Perfumer' })
  const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '' })
  const [emailForm, setEmailForm] = useState({ currentPassword: '', newEmail: '' })
  useEffect(() => {
    setNotice(null)
    if (active === 'members') void Promise.all([request<{ members: typeof members }>('/workspace/members'), request<{ invitations: V2Invitation[] }>('/workspace/invitations')]).then(([memberPayload, invitationPayload]) => { setMembers(memberPayload.members); setInvitations(invitationPayload.invitations) }).catch((error) => setNotice(error instanceof Error ? error.message : text.noAccess))
  }, [active, text.noAccess])
  const post = async (path: string, body?: unknown) => { setNotice(null); try { await request(path, { method: 'POST', body: body === undefined ? undefined : JSON.stringify(body) }); setNotice('Saved securely.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Request failed') } }
  const requiredPermission: Record<string, string> = { security: 'security.sessions.view', members: 'members.view', domains: 'domains.view', billing: 'billing.capabilities', notifications: 'notifications.view', observability: 'observability.view', workspace: 'tenant.view' }
  if (requiredPermission[active] && session?.capabilities?.[requiredPermission[active]] !== true) return <div className="v2-panel"><h2>{text.noAccess}</h2><p>Access is enforced by the workspace role policy.</p></div>
  if (active === 'billing') return <div className="v2-panel"><h2>{text.billing}</h2><p>Self-service billing is disabled during managed beta. Workspace access and capability limits remain enforced server-side.</p></div>
  if (active === 'security') return <div className="v2-panel"><h2>{text.security}</h2><p>Sessions are opaque, rotated, hash-only, and protected by CSRF for unsafe requests.</p><form className="v2-inline-form" onSubmit={(event) => { event.preventDefault(); void post('/security/password', passwords); setPasswords({ currentPassword: '', newPassword: '' }) }}><label>Current password<input type="password" required value={passwords.currentPassword} onChange={(event) => setPasswords({ ...passwords, currentPassword: event.target.value })} /></label><label>New password<input type="password" required minLength={12} value={passwords.newPassword} onChange={(event) => setPasswords({ ...passwords, newPassword: event.target.value })} /></label><button className="v2-secondary-button" type="submit">Change password</button></form><form className="v2-inline-form" onSubmit={(event) => { event.preventDefault(); void post('/security/email', emailForm); setEmailForm({ currentPassword: '', newEmail: '' }) }}><label>New email<input type="email" required value={emailForm.newEmail} onChange={(event) => setEmailForm({ ...emailForm, newEmail: event.target.value })} /></label><label>Current password<input type="password" required value={emailForm.currentPassword} onChange={(event) => setEmailForm({ ...emailForm, currentPassword: event.target.value })} /></label><button className="v2-secondary-button" type="submit">Change email</button></form>{notice ? <div className="v2-alert" role="status">{notice}</div> : null}</div>
  if (active === 'privacy') return <div className="v2-panel"><h2>{text.privacy}</h2><p>Personal export and workspace export are separate authorization boundaries.</p><button className="v2-secondary-button" type="button" onClick={() => void post('/workspace/exports/privacy')}>{text.export}</button><button className="v2-secondary-button" type="button" onClick={() => void post('/workspace/consents', { purpose: 'PRIVACY', policyVersion: 'v2-2026-08' })}>{text.consent}</button>{notice ? <div className="v2-alert" role="status">{notice}</div> : null}</div>
  if (active === 'members') return <div className="v2-panel"><h2>{text.members}</h2>{session?.capabilities?.['members.invite'] ? <form className="v2-inline-form" onSubmit={async (event) => { event.preventDefault(); await post('/workspace/invitations', inviteForm); setInviteForm({ email: '', role: 'Perfumer' }); const refreshed = await request<{ invitations: V2Invitation[] }>('/workspace/invitations').catch(() => ({ invitations: [] })); setInvitations(refreshed.invitations) }}><label>Invite email<input type="email" required value={inviteForm.email} onChange={(event) => setInviteForm({ ...inviteForm, email: event.target.value })} /></label><label>Role<select value={inviteForm.role} onChange={(event) => setInviteForm({ ...inviteForm, role: event.target.value })}>{['Admin', 'Lab Manager', 'Perfumer', 'R&D Scientist', 'Lab Technician', 'Procurement', 'Sensory Panelist', 'Brand', 'Supplier', 'Finance', 'Viewer'].map((role) => <option key={role}>{role}</option>)}</select></label><button className="v2-secondary-button" type="submit">Invite member</button></form> : null}<div className="v2-member-list">{members.map((member) => <div className="v2-member-row" key={`${member.email}-${member.role}`}><strong>{member.displayName}</strong><span>{member.email}</span><span>{member.role}</span><span>{member.status}</span></div>)}</div>{invitations.filter((item) => item.status === 'PENDING').map((invitation) => <div className="v2-member-row" key={invitation.id}><strong>Pending invitation</strong><span>{invitation.email}</span><span>{invitation.role}</span><button type="button" className="v2-text-button" onClick={async () => { await post(`/workspace/invitations/${invitation.id}/resend`, undefined); const refreshed = await request<{ invitations: V2Invitation[] }>('/workspace/invitations').catch(() => ({ invitations: [] })); setInvitations(refreshed.invitations) }}>Resend</button><button type="button" className="v2-text-button" onClick={async () => { await post(`/workspace/invitations/${invitation.id}/revoke`, undefined); setInvitations(invitations.map((item) => item.id === invitation.id ? { ...item, status: 'REVOKED' } : item)) }}>Revoke</button></div>)}{notice ? <div className="v2-alert" role="status">{notice}</div> : null}</div>
  if (active === 'domains') return <div className="v2-panel"><h2>{text.domains}</h2><p>System hostname is active. Customer-owned domains remain pending until validation and SSL confirmation.</p></div>
  if (active === 'notifications') return <div className="v2-panel"><h2>{text.notifications}</h2><p>In-app, email, and web-push delivery preferences are tenant-scoped.</p></div>
  if (active === 'observability') return <ObservabilityPanel text={text} />
  return <div className="v2-panel"><h2>{text.product}</h2><p>Platform Security Core is active. Lab and scientific modules remain outside this Phase 1 surface.</p></div>
}

function ObservabilityPanel({ text }: { text: PlatformCopy }) {
  const [status, setStatus] = useState<Record<string, string> | null>(null)
  useEffect(() => { void request<{ observability: Record<string, string> }>('/workspace/observability').then((payload) => setStatus(payload.observability)).catch(() => setStatus(null)) }, [])
  return <div className="v2-panel"><h2>{text.observability}</h2>{status ? <div className="v2-member-list">{Object.entries(status).filter(([key]) => key !== 'capturedAt' && key !== 'degradedCount').map(([key, value]) => <div className="v2-member-row" key={key}><strong>{key}</strong><span>{value}</span></div>)}</div> : <p>{text.noAccess}</p>}</div>
}
